server:
  port: 80
wechat:
  #  微信公众平台的appID
  appId: ''
  #  微信公众平台的appSecret
  secret: ''
  #  百度地图开放平台的城市ID
  district_id: '340100'
  #  百度地图开放平台的应用AK
  ak: ''
  #  纪念日：注意格式yyyy-MM-dd
  loveDate: '2021-08-23'
  #  生日：注意格式yyyy-MM-dd
  birthday: '1998-08-23'
  #  模板ID
  templateId: ''
  #  天行数据apiKey
  rainbowKey: ''
  #  关注公众号的用户ID（要推送的人的用户ID,在微信公众平台里可以查看到,现在支持推送多个人）
  userId:
    - ''
    - ''